/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovenorContract__factory } from "./GovenorContract__factory";
export { GovernorContract__factory } from "./GovernorContract__factory";
