/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovenorContract } from "./GovenorContract";
export type { GovernorContract } from "./GovernorContract";
